name: Build Android APK

# 触发条件：推送或PR到main/master分支时运行
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    # 运行环境：Ubuntu最新版
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v4  # 使用最新稳定版

      # 步骤2：配置Python环境（buildozer依赖Python）
      - name: Set up Python
        uses: actions/setup-python@v5  # 最新版
        with:
          python-version: '3.9'  # 推荐3.8+，兼容buildozer

      # 步骤3：安装系统级依赖（Android构建必需）
      - name: Install system dependencies
        run: |
          sudo apt-get update
          # 安装Java（Android构建需要）、zlib等依赖
          sudo apt-get install -y openjdk-11-jdk zlib1g-dev libncurses5-dev \
            libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget

      # 步骤4：安装Python依赖（buildozer、cython等）
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer  # 用于构建APK的工具
          pip install cython  # 解决之前的"cython未找到"错误

      # 步骤5：初始化buildozer（生成配置文件，若项目中已有可省略）
      - name: Initialize buildozer
        run: buildozer init

      # 步骤6：构建Android APK（debug版本）
      - name: Build APK
        run: buildozer android debug

      # 步骤7：上传构建好的APK作为产物（方便下载）
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4  # 最新版，解决弃用问题
        with:
          name: app-apk
          path: bin/*.apk  # APK默认生成在bin目录下
